version: '3.5'

services:
  producer:
    image: rrojas/account-transaction-producer:1.0
    build:
      context: bank-balance-producer
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafkastreams-network

  aggregator:
    image: rrojas/account-balance-stream:1.0
    build:
      context: bank-balance-stream
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks